config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'

  get  'help'   => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'search', to: 'search#search'
  get  'advanced_search', to: 'search#advanced_search'
  resources :search_suggestions, only: :index

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: :show
  resources :advertisements do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end
  resources :vehicle_models
  resources :vehicle_brands, only: [:index, :show]
  resources :options

  resources :categories, only: [:index, :show] do
    member do
      get "basic", to: "categories#basic"
      get "additional", to: "categories#additional"
      get "options", to: "categories#options"
    end
  end

  resources :information, only: :index do
    member do
      get 'items', to: 'informations#items'  
    end  
  end
end

app/views/shared/_advertisement_front.html.erb
	<% if index % 3 == 0 %>
		<div class="row" id="advertisement_row_<%= index %>">
	<% end %>		
			
	<div class="col-md-4">
		<div class="advertisement_front">
		<%= link_to advertisement do %>
			<div class="thumbnail">
				<%# image = advertisement.images? ? advertisement.images[0].thumb_middle.url : "placeholder.png" %>
				<% image = advertisement.featured_image? ? advertisement.featured_image.url : "placeholder.png" %>
				<%= image_tag(image, class: "img-responsive") %>

				<div class="caption">
					<h4><%= advertisement.title %></h4>
					<p><b>Price:</b> <%= number_with_precision advertisement.price, precision: 2 %> €</p>
					<p><b>Category:</b> <%= advertisement.category.name %></p>
				</div>
			</div>
		<% end %>
		</div>					
	</div>
	
	<% if index % 3 == 2 %>
		</div><!-- row -->
	<% end %>	

app/views/shared/_advertisement_search.html.erb
	<% if index % 4 == 0 %>
		<div class="row" id="advertisement_row_<%= index %>">
	<% end %>		
			
	<div class="col-md-3">
		<div class="advertisement_front">
		<%= link_to advertisement do %>
			<div class="thumbnail">
				<%# image = advertisement.images? ? advertisement.images[0].thumb_middle.url : "placeholder.png" %>
				<% image = advertisement.featured_image? ? advertisement.featured_image.url : "placeholder.png" %>
				<%= image_tag(image, class: "img-responsive") %>

				<div class="caption">
					<h4><%= advertisement.title %></h4>
					<p><b>Price:</b> <%= number_with_precision advertisement.price, precision: 2 %> €</p>
					<p><b>Category:</b> <%= advertisement.category.name %></p>
				</div>
			</div>
		<% end %>
		</div>					
	</div>
	
	<% if index % 4 == 3 %>
		</div><!-- row -->
	<% end %>	

app/views/shared/_category_buttons.html.erb
<div class="btn-group btn-group-justified" role="group">
	<% @categories.each do |category| %>
	  <div class="btn-group" role="group">
	  	<% if category.name.eql?("Cars") %>
				<%= link_to category.name, root_path, class: "btn btn-primary", type: "button", disabled: get_disabled_state(category) %>
	  	<% else %>
	  		<%= link_to category.name, category, class: "btn btn-primary", type: "button", disabled: get_disabled_state(category) %>
  		<% end %>
	  </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 	<div id="error_explanation">
 		<div class="alert alert-danger">
 			The form contains <%= pluralize(object.errors.count, "error") %>.
 		</div>	
 		<ul>
 			<% object.errors.full_messages.each do |msg| %>
 				<li><%= msg %></li>
 			<% end %>
 		</ul>		
 	</div>
<% end %> 

app/views/shared/_sidebar.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary" style="margin-top: 53px">
			<%= form_tag search_path, method: :get do %>
			  	<div class="input-group">
			    	<%= text_field_tag :q, params[:q], class: "form-control search_term", placeholder: "Search..." %>
			    	<span class="input-group-btn">
			    		<%= button_tag(type: 'submit', class: "btn btn-primary", 
			    			id: "search_button") do %>
			    			<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
			    		<% end %>
			    	</span>
			  	</div>
			<% end %>
		</div>

		<hr />

		<h3>Advanced Search</h3>

		<%= form_tag advanced_search_path, method: :get do %>		
			<div class="panel panel-primary">
			  <div class="panel-heading">
			    <h3 class="panel-title">Vehicle Brands and Models</h3>
			  </div>
			  <div class="panel-body">
			    <%= label_tag :vehicle_brand, "Vehicle brand: " %><br />    
					<%= select_tag "search_vehicle_brand", options_from_collection_for_select(@vehicle_brands, "id", "name") , prompt: "Select...", class: "form-control" %>
			  	
			  	<br />

			    <%= label_tag :vehicle_model, "Vehicle model: " %><br />    
					<%= select_tag "search_vehicle_model", {}, class: "form-control", 
					disabled: true %>
			  </div>
			</div>

			<div class="panel panel-primary">
			  <div class="panel-heading">
			    <h3 class="panel-title">Price</h3>
			  </div>
			  <div class="panel-body">
			  	<div class="row">
				    <div class="col-md-5">
				    	<%= raw generate_price_select("min_price", "min_price") %>
				    </div>	

						<div class="col-md-2">to</div>							

						<div class="col-md-5">
				    	<%= raw generate_price_select("max_price", "max_price") %>
				    </div>
			    </div>
			  </div>
			</div>

			<div class="panel panel-primary">
			  <div class="panel-heading">
			    <h3 class="panel-title">Year</h3>
			  </div>
			  <div class="panel-body">
			  	<div class="row">
				    <div class="col-md-5">
				    	<%= select_tag "year", options_for_select((1980..Date.today.year).to_a), class: "form-control", id: "min_year", name: "min_year", prompt: "Any" %>
				    </div>	

						<div class="col-md-2">to</div>							

						<div class="col-md-5">
				    	<%= select_tag "year", options_for_select((1980..Date.today.year).to_a), class: "form-control", id: "max_year", name: "max_year", prompt: "Any" %>
				    </div>
			    </div>
			  </div>
			</div><!-- panel -->

			<% Category.search_options(@category.name).each_with_index do |option, index| %>
				<%= print_sidebar_panel(option[:title], option[:select_name], option[:items_name]) %>
			<% end %>

			<%= hidden_field_tag(:category, @category.id) %>

			<%= button_tag "Search", type: 'submit', class: 'btn btn-primary btn-block', id: 'advanced_search_button' %>
		<% end %>
	</div>
</div><!-- row -->

<script>
$("#q").autocomplete({
	source: '/search_suggestions',
});
</script>