config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'

  get  'help'   => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'search', to: 'search#search'
  get  'advanced_search', to: 'search#advanced_search'
  resources :search_suggestions, only: :index

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: :show
  resources :advertisements do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end
  resources :vehicle_models
  resources :vehicle_brands, only: [:index, :show]
  resources :options

  resources :categories, only: [:index, :show] do
    member do
      get "basic", to: "categories#basic"
      get "additional", to: "categories#additional"
      get "options", to: "categories#options"
    end
  end

  resources :information, only: :index do
    member do
      get 'items', to: 'informations#items'  
    end  
  end
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]

	belongs_to :advertisement_type
	belongs_to :user, validate: true
	belongs_to :category, validate: true
	belongs_to :vehicle_model, validate: true
	has_and_belongs_to_many :options, autosave: true
	has_many :advertisement_informations, autosave: true, dependent: :destroy
	has_many :informations, through: :advertisement_informations
	has_many :comments

	# this creates advertisement_informations_attributes= method on Advertisement that allows
	# create, update and delete destroy advertisement_informations
	accepts_nested_attributes_for :advertisement_informations
	accepts_nested_attributes_for :options

	serialize :images, Array
	# picture - name of the attribute
	mount_uploaders :images, ImageUploader

	mount_uploader :featured_image, FeaturedImageUploader

	validates :title, presence: true
	validates :price, presence: true
	validates :year, presence: true
	validates :vehicle_model, presence: true
	validates :user, presence: true

	# active - 0, inactive - 1, pending - 2, rejected - 3
	enum status: [:active, :inactive, :pending, :rejected]

	scope :active, -> { where(status: self.statuses[:active]) }
  scope :title_like_term, -> (term) { where("title like ?", "%#{term}%") }
	after_commit :send_email, if: :status_changed?

  # Refactoring =====================================================================================
  def get_basic_advertisement_information
    basic_information_id = InformationType.get_id_by_name("Basic")
    return if basic_information_id.nil?

    basic_advertisement_informations = create_initial_information_array_for(basic_information_id)

    fill_initial_arr_for(basic_advertisement_informations)
  end

  def get_additional_advertisement_information
    additional_information_id = InformationType.get_id_by_name("Additional")
    return if additional_information_id.nil?

    additional_advertisement_informations = create_initial_information_array_for(additional_information_id)

    fill_initial_arr_for(additional_advertisement_informations)
  end

  def create_initial_information_array_for(id)
    information_arr = {}

    informations.each do |info|
      if info.information_type.id == id
        information_arr[info.name] = ""
      end
    end

    information_arr
  end

  def fill_initial_arr_for(information_arr)
    return if information_arr.nil? or information_arr.empty?

    advertisement_informations.each do |adv_info|
      if information_arr.has_key?(adv_info.information.name)
        information_arr[adv_info.information.name] = adv_info.value
      end     
    end

    information_arr
  end
  #=================================================================================================

	# TODO - ovo refaktorisati
	def save_all advertisement_informations
    set_advertisement_informations unless advertisement_informations.nil?

  	self.pending!
		self.save!
	end

  def set_advertisement_informations
    advertisement_informations.each do |info_id, value|
      a = new_advertisement_information(info_id, value)
      self.advertisement_informations << a
    end
  end

  def new_advertisement_information(info_id, value)
    return if info_id.nil? or value.nil? or value.eql?("")

    information = find_information(info_id)
    return if information.nil?

    AdvertisementInformation.new(
      advertisement: self,
      information: information,
      value: value
    )
  end

  def find_information(id)
    begin
      Information.find(id)
    rescue
      nil
    end
  end

  #=================================================================================================

	def update_all(advertisement_params, informations)
		self.advertisement_informations.each do |info|
			informations.each do |key, value|
				if key.to_i == info.information_id.to_i
					info.value = value
				end
			end
		end

		return self.update(advertisement_params)
	end

	def get_information type
		id = InformationType.find_by(name: type).id
		arr = []

		informations.each do |info|
			if info.information_type_id == id
  				arr << info
  			end
		end

		return arr
	end

	# filter out empty options
	def self.get_options params
		arr = params.to_a
		ret_val = []

		arr.each do |el|
			if el[1]["name"].count == 2 && el[1]["name"].include?("1")
				ret_val << el[1]["id"].to_i
			end
		end

		return ret_val
	end

	def slug_candidates
		[
       		:title,
       		[:title, :year],
       		[:title, :year, :price]
		]
    end

    def self.search(q, paginate)
    	q.gsub!(/[^a-zA-Z0-9\-]/," ") 
    	search = q.split
    	results = none

    	if search.size == 0 
    		results = all
    	elsif search.size == 1
    		results = Advertisement
					.left_outer_joins(:advertisement_informations)
					.joins(vehicle_model: :vehicle_brand)
					.select("advertisements.*, vehicle_models.name, vehicle_brands.name")
					.where("advertisements.title LIKE ? OR advertisement_informations.value LIKE ? OR vehicle_brands.name LIKE ? OR vehicle_models.name LIKE ?",
							 "%#{search.first}%", "%#{search.first}%", "%#{search.first}%", "%#{search.first}%")
					.distinct
        elsif search.size > 1
        	searchable_columns = ["advertisements.title", 
        						  "advertisement_informations.value", 
        						  "vehicle_brands.name"]
        	
        	query = search.map do |term|
        	 	fields = searchable_columns.map do |column|
        	 		" #{column} LIKE #{sanitize("%#{term}%")}"
      			end
        	end.join(' OR ')

        	results = Advertisement
    				.joins(:advertisement_informations)
    				.joins(vehicle_model: :vehicle_brand)
    				.select("advertisements.*, vehicle_models.name, vehicle_brands.name")
    				.where(query)
    				.distinct
    	else
    		results = all
    	end

    	results
    		.active
	    	.paginate(page: paginate, per_page: 9)
            .order('created_at DESC')	
    end

    def self.advanced_search(params, paginate)
    	params.select! {|key, value| !key.eql?("controller")}
    	params.select! {|key, value| !key.eql?("action")}
    	params.select! {|key, value| !key.eql?("utf8") }
    	#remove empty params
    	category = Category.find(params[:category])
    	params.select! {|key, value| !value.eql?("")}
    	params.select! {|key, value| !key.eql?("category")}
    	query = ""
    	fields = []
    	vehicle_brand_exits  = false
    	fuel_exists = false
    	engine_exists = false
    	drive_exists = false
    	air_condition_exists = false
    	transmission_exists = false
    	exterior_color_exists = false

    	params.each do |key, value|	
    		if key.eql?("min_price") 
    			fields << " price > #{value} "
    		end

			if key.eql?("max_price") 
    			fields << " price < #{value} "
    		end			    	

			if key.eql?("min_year") 
				date = Time.new(value.to_i - 1).year
    			fields << " year > '#{date}' "
    		end 

    		if key.eql?("max_year") 
				date = Time.new(value.to_i + 1).year
    			fields << " year < '#{date}' "
    		end  

    		if key.eql?("search_vehicle_model") 
    			fields << " vehicle_model_id = #{value} " 
    		end 

    		if key.eql?("search_vehicle_brand") 
    			vehicle_brand_exits = true
    			fields << " vehicle_brand_id = #{value} " 
    		end     			

			if key.eql?("fuel") 
    			fuel_exists = true
    			information_id = Information.find_by(name: "Fuel").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} AND value LIKE '#{information_value}' " 
    		end    

    		if key.eql?("engine") 
    			engine_exists = true
    			information_id = Information.find_by(name: "Engine").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} and value LIKE '#{information_value}' " 
    		end 

    		if key.eql?("drive") 
    			drive_exists = true
    			information_id = Information.find_by(name: "Drive").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} and value LIKE '#{information_value}' " 
    		end

    		if key.eql?("air_condition") 
    			air_condition_exists = true
    			information_id = Information.find_by(name: "Air Condition").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} and value LIKE '#{information_value}' " 
    		end   

    		if key.eql?("transmission") 
    			transmission_exists = true
    			information_id = Information.find_by(name: "Transmission").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} and value LIKE '#{information_value}' " 
    		end 

    		if key.eql?("exterior_color") 
    			exterior_color_exists = true
    			information_id = Information.find_by(name: "Exterior Color").id
    			information_value = Item.find(value).name
    			fields << " information_id = #{information_id} and value LIKE '#{information_value}' " 
    		end     			    		
		end
		query = fields.join(" AND ")

		results = category.advertisements			

		if vehicle_brand_exits
			results = results.joins(vehicle_model: :vehicle_brand)
		end

		if(fuel_exists || engine_exists || drive_exists || air_condition_exists || transmission_exists || exterior_color_exists)
			results = results.joins(:advertisement_informations)
		end

		results = results.where(query)    	

    	results
    		.active
	    	.paginate(page: paginate, per_page: 9)
            .order('created_at DESC')
    end

    private

    def status_changed?
    	if !pending?
    		ret_val = previous_changes.has_key?("status")
    	end
    end

    def send_email
    	@advertisement = self
		UserMailer.advertisement_updated(user.email, self).deliver_now
    end

end

app/models/advertisement_type.rb
class AdvertisementType < ApplicationRecord
	has_many :advertisements
	
	validates :name, presence: :true
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController

  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show

  load_and_authorize_resource only: [:edit, :update, :destroy]
  
  def index
    @advertisements = Advertisement.where('user_id = ?', current_user.id)
  end

  def show    
    @basic_advertisement_informations = @advertisement.get_basic_advertisement_information
    @additional_advertisement_informations = @advertisement.get_additional_advertisement_information
    @options = @advertisement.options
    @comments = prepare_comments(@advertisement.comments)
  end

  def new
    @advertisement = Advertisement.new
    @categories = Category.all
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user = current_user
    @advertisement.option_ids = params[:advertisement][:options_attributes]

    #advertisement_informations = params[:advertisement][:advertisement_informations]
    advertisement_informations = get_advertisement_informations params[:advertisement][:advertisement_informations]

    if @advertisement.save_all(advertisement_informations)
      UserMailer.advertisement_created(current_user.email, @advertisement.id).deliver_now
      flash[:success] = "Advertisement successfully created."
      redirect_to @advertisement
    else
      flash.now[:notice] = "ERROR: Images count exceeds limit.!"
      render :new
    end
  end

  def edit
    @basic_informations = Category.get_all_category_informations(@advertisement.category.id, "Basic")
    @additional_informations = Category.get_all_category_informations(@advertisement.category.id, "Additional")
    @all_options = @advertisement.category.options
  end

  def update
    informations = get_advertisement_informations params[:advertisement][:advertisement_informations]
    @advertisement.option_ids = Advertisement.get_options params[:advertisement][:options_attributes]

    if @advertisement.update_all(advertisement_params, informations)
      flash[:success] = "Advertisement successfully updated."
      redirect_to @advertisement
    else
      @basic_informations = Category.get_all_category_informations(@advertisement.category.id, "Basic")
      @additional_informations = Category.get_all_category_informations(@advertisement.category.id, "Additional")
      @all_options = @advertisement.category.options#

      flash.now[:notice] = "ERROR: Updating advertisement.Please try again.Thank you!"
      render :edit
    end
  end

  def destroy
    @advertisement.destroy

    redirect_to advertisements_path
  end

  private 

  def set_advertisement
    @advertisement = Advertisement.friendly.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :price, :year, :category_id, :featured_image, 
                                          :vehicle_model_id, :user_id, :advertisement_type_id,
                                          :option_ids, :advertisement_informations, images: [])
  end

  # we have to check is Item with given id exists or is it a value
  def get_advertisement_informations(in_params)  
    in_params ||= []  
    ret_arr = {}
    in_params.each do |key, value|
      value = (Item.exists?(value) ? value = Item.find(value).name : value)
      ret_arr[key] = value
    end

    return ret_arr
  end

  def prepare_comments(comments)
    comments.map do |comment|
      {
        id: comment.id,
        author: comment.author,
        body: comment.body,
        created_at: comment.created_at.to_formatted_s(:long),
        advertisement_id: comment.advertisement_id,
        parent_id: comment.parent_id,
        rank: comment.rank
      }
    end
  end

end

app/views/advertisements/_advertisement.html.erb
<tr>
	<td><%= advertisement.title %></td>
	<td><i><%= advertisement.category.name %></i></td>
	<td><%= advertisement.created_at %></td>
	<td>
		<%= link_to "View",   advertisement_path(advertisement), class: "btn btn-primary" %> </td>
	<td>	
		<%= link_to "Edit",   edit_advertisement_path(advertisement), class: "btn btn-primary" %> </td>
	<td>
		<%= link_to "Delete", advertisement, data: {
											confirm: 'Are you shure?'
											}, method: :delete, class: "btn btn-danger" %> 
	</td>
</tr>

app/views/advertisements/edit.html.erb
<% provide(:title, "Edit advertisement") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3 class="text-muted">Edit Advertisement</h3>	
		
		<%= form_for(@advertisement, html: { class: "advertisement", id: "advertisement_form"}) do |f| %>

			<%= render 'shared/error_messages', object: f.object %>

			<div class="row">
	  		<div class="col-sm-4">
    			<h4>Category: <i><%= @advertisement.category.name %></i></h4>
				</div>
			</div>
			<hr />

			<div class="form-group">
		    <%= f.label :title, "Title: *" %> <br />
		    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		    <%= f.label :description, "Description:" %> <br />
		    <%= f.text_area :description, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		  	<div class="row">
		  		<div class="col-sm-4">
		    		<%= f.label :price, "Price(€): *" %>    
		    		<%= f.text_field :price, size: 20, placeholder: "000.000" %> 
		    	</div>

		    	<div class="col-sm-4">
		    		<%= f.label :year, "Year: *" %>    
		    		<%= f.text_field :year, placeholder: "Click here", id: "advertisement_year" %> 
		    	</div>
		    </div>
		  </div>

		  <hr />

			<h4 class="text-info">Basic information</h4>
			<br />

			<div id="basic_informations">
				<% index = 0 %>
				<%= f.fields_for :advertisement_informations, @basic_informations do |advertisement_information| %>
					<% if advertisement_information.object.items.empty? %>
							<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true
	    								%>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true 
	    								%>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true 
	    								%>
										</div>
							<% end %>
					<% else %>
						<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
							<% end %>
					<% end %>
					
					<% index = index.to_i + 1 %>
				<% end %>
			</div><!-- basic_information -->

			<hr />

			<h4 class="text-info">Additional information</h4>
			<br />

			<div id="additional_informations">
				<% index = 0 %>
				<%= f.fields_for :advertisement_informations, @additional_informations do |advertisement_information| %>
					<% if advertisement_information.object.items.empty? %>
							<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
							<% end %>
					<% else %>

						<% if index % 3 === 0 %>
								
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
							<% elsif index % 3 == 2 %>
										
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
							<% end %>
					<% end %>
					
					<% index = index.to_i + 1 %>
				<% end %>
			</div><!-- basic_information -->

			<hr />


		<div class="form-group">
		  	<div class="row">
		  		<div class="col-sm-8">
		    		<label>Featured Image</label>
				    <%= image_tag(@advertisement.featured_image_url) if @advertisement.featured_image? %>
					<%= f.file_field :featured_image %>
					<%= f.hidden_field :featured_image_cache %>
		    	</div>
		    </div>
		</div>	

		<h4 class="text-info">Options</h4>	
	  	<br />	  	
	  	<div id="options">
	  	<% index = 0 %>
	  	<%= f.fields_for :options, @all_options do |option| %>	
					<% if index % 4 === 0 %>
						<div class='form-group'>
							<div class='row'>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>
									</div>
								</div>
					<% elsif index % 4 === 3 %>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>	
									</div>
								</div>
							</div>
						</div>
					<% else %>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>
									</div>
								</div>
					<% end %>						
				<% index = index.to_i + 1 %>
			<% end %>
			</div>

			<hr />
			<div class="picture">
				<h3>
				<span class="label label-info">For multiple image selection use SHIFT+SELECT or CTRL+SELECT
				</span>
				</h3>
				<br/>
				<%= f.file_field :images, multiple: true, accept: 'image/jpeg,image/gif,image/png' %>
			</div>

			<br /><br />
			<%= f.submit "Edit advertisement", class: "btn btn-primary" %>
			<br /><br />
				
			<hr />

		<% end %>
		
	</div>
</div>	

<%= javascript_include_tag "advertisements" %>

app/views/advertisements/index.html.erb
<% provide(:title, "All Advertisements") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
        <div class="list-group">
      		<h3>Yours Advertisements</h3>
  		    <br />
            <%= link_to "New Advertisement", new_advertisement_path, class: "btn btn-primary" %> </td>
            <hr />
	
        	<div class="table-responsive">
      			<table class="table table-striped table-hover">
      				<thead>
      					<tr>
      						<th>Title</th>
      						<th>Category</th>
      						<th>Date</th>
      					</tr>
      				</thead>
      				<tbody>
        				<%= render @advertisements %>
        			</tbody>
      			</table>
    		</div>
		</div>
    </div>
</div>

app/views/advertisements/new.html.erb
<% provide(:title, "New advertisement") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3 class="text-muted">New Advertisement</h3>	
		
		<%= render 'form' %>

		<div class="text-center" id="spinner"></div>
	</div>
</div>	